# Generated by Django 5.2.6 on 2025-09-22 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField()),
                ('quantidade_entrada', models.IntegerField()),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_vendida', models.IntegerField(default=0)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_estoque', to='produtos.produto')),
            ],
        ),
    ]
